### ISSUE TITLE
add the ‘hacktoberfest’ topic to the repository to opt the project into Hacktoberfest

### ISSUE THREAD

**Issue by romanlazunin** [NikolaiVChr/sublime-nasal#2]
Hi, would you like to tag the repo with 'hacktoberfest' so opt in project for hacktoberfest contributions please?

According to instructions in https://hacktoberfest.com/participation/#contributors

Thank you!

**Comment by NikolaiVChr** [comment]
This repo is not very active so it wont earn the badge anyway.
But thanks for the link.

**Comment by romanlazunin** [comment]
Good! I'm just updating awesome-flightgear and come around your plugin which I installed for my Sublime. I thought probably I could make some light hacktoberfest contribution to you documentation/readme like screenshot or gif. I can still make a PR and kindly ask you to tag PR itself with hacktoberfest-accepted later then. It would work as well for my sake, no worries! 
Thank you!
